### ISSUE TITLE
upgrade to wheel-picker 1.1.3 

### ISSUE THREAD

**Issue by chj-damon** [abbasmoosavi/react-native-best-wheel-datepicker#5]
wheel-picker is now at 1.1.3, but you're still using 1.0.3. maybe it's better to support the latest version?

**Comment by abbasmoosavi** [comment]
> wheel-picker is now at 1.1.3, but you're still using 1.0.3. maybe it's better to support the latest version?

Now, i updated to 1.1.3 and fixed in 0.0.8 version of package
